{{- if .Values.ingress.enabled -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /home
        backend:
          serviceName: {{ .Values.frontendService.name }}
          servicePort: {{ .Values.frontendService.port }}
  - host: 
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Values.backendService.name }}
          servicePort: {{ .Values.backendService.port }}

{{- end }}
