apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "books-trade-postgre-chart.fullname" . }}
type: Opaque
data:
  db-username: {{ .Values.db.username }}
  db-password: {{ .Values.db.password }}
  queue-username: {{ .Values.queue.username }}
  queue-password: {{ .Values.queue.password }}
